spryk: template
description: "Adds a new *module*Facade to the Zed application."
mode: project
level: 2

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Pyz

    template:
        value: Zed/Business/ZedBusinessFacade.php.twig

    targetFilename:
        value: "{{ module }}Facade.php"

    targetPath:
        value: "src/{{ organization }}/Zed/{{ module }}/Business/"

preSpryks:
    - AddModule

postSpryks:
    - AddZedBusinessFacadeInterface
    - AddZedBusinessFactory
