spryk: template
description: "Adds a new Business Model reader to the Zed application."
mode: both
level: 3

arguments:
    module:
        inherit: true

    organization:
        inherit: true
        default: Pyz

    template:
        value: Zed/Business/Model/Writer/ZedBusinessModelWriter.php.twig

    targetFilename:
        value: "{{ module }}Writer.php"

    targetPath:
        value: "src/{{ organization }}/Zed/{{ module }}/Business/Module/Writer"
